"use client";
import "./globals.css";
//react-bootstrap-css
import "bootstrap/dist/css/bootstrap.min.css";

//components
import Header from "@/components/UI/Header";

//redux
import { Provider } from "react-redux";
import store from "@/store/store";

//next-auth
import { SessionProvider } from "next-auth/react";

// export const metadata = {
//   title: "Licence Shop",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Provider store={store}>
            <Header />
            {children}
          </Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
